"""fourth

Revision ID: 109167577b0e
Revises: 1fed7921bcc2
Create Date: 2023-02-09 00:34:56.610700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '109167577b0e'
down_revision = '1fed7921bcc2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_guides', sa.Column('luggage_weight', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'flight_guides', ['flight_number'])
    op.create_unique_constraint('_role_permission_uc', 'role_permissions', ['role_id', 'permission_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_role_permission_uc', 'role_permissions', type_='unique')
    op.drop_constraint(None, 'flight_guides', type_='unique')
    op.drop_column('flight_guides', 'luggage_weight')
    # ### end Alembic commands ###
