"""Second

Revision ID: 159f2a1943c7
Revises: beca800d2075
Create Date: 2022-11-28 20:43:14.787340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '159f2a1943c7'
down_revision = 'beca800d2075'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rub_to_usd', sa.Float(), nullable=True),
    sa.Column('rub_to_eur', sa.Float(), nullable=True),
    sa.Column('rub_to_uzs', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currency_rates_id'), 'currency_rates', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currency_rates_id'), table_name='currency_rates')
    op.drop_table('currency_rates')
    # ### end Alembic commands ###
