"""therd

Revision ID: 1fed7921bcc2
Revises: 454a24d1185d
Create Date: 2023-02-08 17:32:26.006726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fed7921bcc2'
down_revision = '454a24d1185d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('is_booked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'is_booked')
    # ### end Alembic commands ###
