"""second

Revision ID: 454a24d1185d
Revises: d42a9ece4648
Create Date: 2023-02-08 11:47:05.918377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454a24d1185d'
down_revision = 'd42a9ece4648'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=510), nullable=True),
    sa.Column('code', sa.String(length=3), nullable=True),
    sa.Column('description', sa.String(length=510), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=True)
    op.create_table('flight_guides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('flight_number', sa.String(length=255), nullable=False),
    sa.Column('from_airport_id', sa.Integer(), nullable=False),
    sa.Column('to_airport_id', sa.Integer(), nullable=False),
    sa.Column('luggage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['from_airport_id'], ['airports.id'], ),
    sa.ForeignKeyConstraint(['to_airport_id'], ['airports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flight_guides_id'), 'flight_guides', ['id'], unique=True)
    op.add_column('airports', sa.Column('code', sa.String(length=3), nullable=True))
    op.add_column('cities', sa.Column('code', sa.String(length=3), nullable=True))
    op.alter_column('countries', 'code',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.drop_column('countries', 'short_name')
    op.add_column('flights', sa.Column('flight_guide_id', sa.Integer(), nullable=False))
    op.drop_constraint('flights_from_airport_id_fkey', 'flights', type_='foreignkey')
    op.drop_constraint('flights_to_airport_id_fkey', 'flights', type_='foreignkey')
    op.create_foreign_key(None, 'flights', 'flight_guides', ['flight_guide_id'], ['id'])
    op.drop_column('flights', 'from_airport_id')
    op.drop_column('flights', 'to_airport_id')
    op.drop_column('flights', 'flight_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('flight_number', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('flights', sa.Column('to_airport_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('flights', sa.Column('from_airport_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'flights', type_='foreignkey')
    op.create_foreign_key('flights_to_airport_id_fkey', 'flights', 'airports', ['to_airport_id'], ['id'])
    op.create_foreign_key('flights_from_airport_id_fkey', 'flights', 'airports', ['from_airport_id'], ['id'])
    op.drop_column('flights', 'flight_guide_id')
    op.add_column('countries', sa.Column('short_name', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    op.alter_column('countries', 'code',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.drop_column('cities', 'code')
    op.drop_column('airports', 'code')
    op.drop_index(op.f('ix_flight_guides_id'), table_name='flight_guides')
    op.drop_table('flight_guides')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
