"""second

Revision ID: b9a857ed2d44
Revises: 662beefb328e
Create Date: 2023-03-06 13:03:10.838923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9a857ed2d44'
down_revision = '662beefb328e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('name_uz', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_types_id'), 'payment_types', ['id'], unique=True)
    op.add_column('refills', sa.Column('payment_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'refills', 'payment_types', ['payment_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refills', type_='foreignkey')
    op.drop_column('refills', 'payment_type_id')
    op.drop_index(op.f('ix_payment_types_id'), table_name='payment_types')
    op.drop_table('payment_types')
    # ### end Alembic commands ###
