"""fifth

Revision ID: deb107e3732e
Revises: 109167577b0e
Create Date: 2023-02-10 14:44:47.315025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deb107e3732e'
down_revision = '109167577b0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_guides', sa.Column('baggage_weight', sa.Integer(), nullable=True))
    op.drop_column('flight_guides', 'luggage_weight')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_guides', sa.Column('luggage_weight', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('flight_guides', 'baggage_weight')
    # ### end Alembic commands ###
