{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .name }}"
  labels:
    {{- include "avialine.labels" $ | nindent 4 }}
    k8s-app: {{ .name }}
spec:
  ports:
  - name: http
    port: {{ .port }}
    targetPort: {{ .port }}
    protocol: TCP
  selector:
    {{- include "avialine.selectorLabels" $ | nindent 4 }}
    k8s-app: {{ .name }}
---
{{- end }}

